practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/models.py
from flask_login import UserMixin          # New import
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

class Employee(db.Model, UserMixin):  # Your class definition
    __tablename__ = "employee"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, nullable=False, unique=True)
    hashed_password = db.Column(db.String(255), nullable=False)

    orders = db.relationship("Order",back_populates="employee")
    details = db.relatioship("OrderDetail", back_populates="employee")

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

class Menu(db.Model):
    __tablename__ = "menus"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    
    items = db.relationship("MenuItem", back_populates="menu")

class MenuItem(db.Model):
    __tablename__ = "menu_items"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    menu_id = db.Column(db.Integer, db.ForeignKey("menus.id"), nullable=False)
    menu_type_id = db.Column(db.Integer, db.ForeignKey("menu_item_types.id"), nullable=False)
    
    menu = db.relationship("Menu", back_populates="items")
    type = db.relationship("MenuItemType", back_populates="menu_type")

class MenuItemType(db.Model):
    __tablename__ = "menu_item_types"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    
    menu_type = db.relationship("MenuItem", back_populates="type")

class Table(db.Model):
    __tablename__ ="tables"

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False, unique=True)
    capacity= db.Column(db.Integer, nullable=False)

    orders = db.relationship("Order", back_populates="table")

class Order(db.model):
    __tablename__="orders"

    id = db.Column(db.Integer, primary_key=True)
    employee_id= db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    table_id= db.Column(db.Integer, db.ForeignKey("tables.id"), nullable=False)
    finished= db.Column(db.Boolean, nullable=False, default=False)

    employee=db.relationship("Employee",back_populates="orders")
    table =db.relationship("Table", back_populates="orders")
    details = db.relationship("OrderDetail", back_populates="order")

class OrderDetail(db.model):
    __tablename__="order_details"

    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey("orders.id"), nullable=False)
    menu_item_id = db.Column(db.Integer, db.ForeignKey("menu_items.id"), nullable=False)

    order=db.relationship("Order", back_populates="details")
    employee=db.relationship("Employee", back_populates="details")

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired
class LoginForm(FlaskForm):
    employee_number = StringField("Employee Number", validators=[DataRequired()] )
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/__init__.py
from flask import Flask
from .config import Configuration
from .models import db, Employee   # New import
from .routes import orders, session
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)  # Configure the application with SQLAlchemy

login = LoginManager(app)
login.login_view = "session.login"


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required
bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/")
@login_required
def index():
    return render_template('orders.html')

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from app.forms import LoginForm
from flask_login import current_user, login_user, logout_user
from app.models import Employee

bp = Blueprint("session", __name__, url_prefix="/session")

@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == empl_number).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)

@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/templates/base.html
<html>

<head>
    {% if title %}
    <title>{{ title }} - Order Up!</title>
    {% else %}
    <title>Welcome to Order Up!</title>
    {% endif %}
</head>

{% if not current_user.is_anonymous %}
<form method="post" action="{{ url_for('session.logout') }}">
    <button>Logout</button>
</form>
{% endif %}

<body>
    {% block content %}{% endblock %}
</body>

</html>

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

practice-for-sprint-18-python-order-up-long-practice-main/practice-for-sprint-18-python-order-up-long-practice-main/app/templates/orders.html
{% extends "base.html" %}

{% block content %}
<h1>Order up!</h1>
{% endblock %}